# Generated by Django 2.2.13 on 2020-10-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=50)),
                ('decision', models.CharField(max_length=9)),
                ('comments', models.TextField(default='')),
                ('decision_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
