# Generated by Django 2.2.13 on 2020-11-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
