# Generated by Django 2.2.13 on 2020-11-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0002_annotation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='user',
            field=models.CharField(default='', max_length=150),
        ),
    ]
