# Generated by Django 2.2.13 on 2021-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0007_auto_20210326_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='background_color',
            field=models.TextField(default='#ffffff'),
        ),
    ]
