# Generated by Django 2.2.13 on 2021-08-02 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0009_usersettings_signal_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_annotations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='when_requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
