# Generated by Django 2.2.13 on 2021-08-07 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0010_auto_20210716_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('last_invite_date', models.DateTimeField()),
                ('joined', models.BooleanField(default=False)),
                ('joined_username', models.CharField(max_length=150, null=True, unique=True)),
            ],
        ),
    ]
