# Generated by Django 2.2.13 on 2021-07-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0011_invitedemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='n_ekg_sigs',
            field=models.IntegerField(default=2),
        ),
    ]
