# Generated by Django 2.2.13 on 2021-08-07 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0011_auto_20210802_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='requested_annotations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='when_requested',
        ),
        migrations.AddField(
            model_name='user',
            name='date_assigned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
