# Generated by Django 2.2.13 on 2021-08-13 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0012_auto_20210807_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='due_date',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
