# Generated by Django 2.2.13 on 2021-08-15 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0015_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_assigned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
