# Generated by Django 2.2.13 on 2021-09-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0016_user_date_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='window_size_min',
            field=models.FloatField(default=15.0),
        ),
    ]
