# Generated by Django 2.2.13 on 2021-09-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0017_auto_20210918_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='margin_bottom',
            field=models.FloatField(default=35.0),
        ),
    ]
