# Generated by Django 2.2.13 on 2021-10-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0018_auto_20210919_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='window_size_min',
            field=models.FloatField(default=10.0),
        ),
    ]
