# Generated by Django 2.2.13 on 2021-10-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0020_auto_20211025_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='signal_std',
            field=models.FloatField(default=6.0),
        ),
    ]
