# Generated by Django 2.2.13 on 2021-10-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0021_auto_20211030_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='practice_status',
            field=models.CharField(choices=[('BG', 'Began'), ('CO', 'Completed'), ('ED', 'Ended')], default='ED', max_length=2),
        ),
    ]
