# Generated by Django 2.2.13 on 2021-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0023_auto_20211116_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adjudicator',
            field=models.BooleanField(default=False),
        ),
    ]
