# Generated by Django 2.2.13 on 2021-12-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0024_user_is_adjudicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='is_adjudication',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
