# Generated by Django 2.2.13 on 2022-11-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0025_annotation_is_adjudication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
