# Generated by Django 2.2.13 on 2022-12-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0026_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_annotator',
        ),
    ]
