# Generated by Django 2.2.13 on 2022-12-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0027_auto_20221221_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entrance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='practice_status',
            field=models.CharField(choices=[('BG', 'Began'), ('CO', 'Completed'), ('ED', 'Ended')], default='BG', max_length=2),
        ),
    ]
