# Generated by Django 2.2.13 on 2023-01-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0028_auto_20221221_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entrance_score',
            field=models.CharField(default='NA', max_length=8),
        ),
    ]
