# Generated by Django 2.2.13 on 2023-05-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0031_auto_20230522_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waveformevent',
            name='event',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='waveformevent',
            name='project',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='waveformevent',
            name='record',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
