# Generated by Django 2.2.13 on 2023-05-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0032_auto_20230522_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waveformevent',
            name='project',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waveformevent',
            name='record',
            field=models.CharField(max_length=50),
        ),
    ]
