# Generated by Django 2.2.13 on 2023-05-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0033_auto_20230522_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='waveformevent',
            name='path',
            field=models.CharField(default='<django.db.models.fields.CharField>/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='waveformevent',
            name='event',
            field=models.CharField(max_length=50),
        ),
    ]
