# Generated by Django 2.2.13 on 2023-05-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0034_auto_20230523_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waveformevent',
            name='path',
        ),
        migrations.AddConstraint(
            model_name='waveformevent',
            constraint=models.UniqueConstraint(fields=('project', 'record', 'event'), name='unique_fields'),
        ),
    ]
