# Generated by Django 2.2.13 on 2023-05-24 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0035_auto_20230523_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='waveform',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='waveforms.WaveformEvent'),
        ),
    ]
