# Generated by Django 2.2.13 on 2023-05-24 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0036_annotation_waveform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='waveform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='waveforms.WaveformEvent'),
        ),
    ]
