# Generated by Django 2.2.13 on 2023-05-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0038_auto_20230524_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='waveformevent',
            name='is_practice',
            field=models.BooleanField(default=False),
        ),
    ]
