# Generated by Django 2.2.13 on 2023-06-06 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0039_waveformevent_is_practice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['waveform__project', 'waveform__record', 'waveform__event']},
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('bookmark_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waveforms.User')),
                ('waveform', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='waveforms.WaveformEvent')),
            ],
            options={
                'ordering': ['waveform__project', 'waveform__record', 'waveform__event'],
            },
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('waveform', 'user'), name='unique_fields'),
        ),
    ]
