# Generated by Django 2.2.13 on 2023-06-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0041_bookmark_is_adjudication'),
    ]

    operations = [
        migrations.AddField(
            model_name='waveformevent',
            name='decision',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
