# Generated by Django 2.2.13 on 2023-06-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0042_waveformevent_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waveformevent',
            name='decision',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
