# Generated by Django 2.2.13 on 2023-08-10 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0043_auto_20230618_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='waveformevent',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
